import { connectDB } from "./db";
import { PlantModel } from "./models/Plant";
import dotenv from "dotenv";

dotenv.config();

const plants = [
  {
    name: 'Róża ogrodowa',
    latinName: 'Rosa',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Rose_flower.jpg',
    species: 'shrub',
    soil: ['loamy', 'silty'],
    waterRequirement: 'medium',
    wateringDesc: 'Podlewaj co 2–3 dni w czasie upałów, raz w tygodniu w pozostałych okresach.',
    sunlight: 'full sun',
    floweringPeriod: { start: 6, end: 9 },
    plantingPeriod: { start: 3, end: 4 },
    heightCm: 120,
    color: ['czerwony', 'biały', 'różowy', 'żółty'],
    compatibleWith: ['Lawenda', 'Kocimiętka'],
    soilPh: 6,
    growthRate: 'medium',
    toxicity: false,
    careTips:
      'Przycinaj wczesną wiosną, usuń przekwitłe kwiaty, regularnie podlewaj w okresach suszy.',
    temp: { min: -20, max: 30 },
    lifespan: 'perennial',
  },
  {
    name: 'Lawenda wąskolistna',
    latinName: 'Lavandula angustifolia',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/5/58/Lavandula_angustifolia_001.JPG',
    species: 'herb',
    soil: ['chalky', 'sandy', 'loamy'],
    waterRequirement: 'low',
    wateringDesc: 'Podlewaj raz na tydzień, tylko gdy ziemia jest bardzo sucha.',
    sunlight: 'full sun',
    floweringPeriod: { start: 6, end: 8 },
    plantingPeriod: { start: 4, end: 5 },
    heightCm: 60,
    color: ['fioletowy'],
    compatibleWith: ['Róża ogrodowa', 'Rozmaryn'],
    soilPh: 7,
    growthRate: 'slow',
    toxicity: false,
    careTips:
      'Nie lubi nadmiaru wody, warto przycinać po kwitnieniu, aby zachować ładny kształt.',
    temp: { min: -15, max: 35 },
    lifespan: 'perennial',
  },
  {
    name: 'Tawuła japońska',
    latinName: 'Spiraea japonica',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Spiraea_x_bumalda.JPG/1280px-Spiraea_x_bumalda.JPG',
    species: 'shrub',
    soil: ['loamy', 'silty'],
    waterRequirement: 'medium',
    wateringDesc: 'Podlewaj umiarkowanie, ziemia powinna być lekko wilgotna.',
    sunlight: 'full sun',
    floweringPeriod: { start: 6, end: 9 },
    plantingPeriod: { start: 4, end: 5 },
    heightCm: 100,
    color: ['różowy', 'biały'],
    compatibleWith: ['Berberys', 'Bukszpan'],
    soilPh: 7,
    growthRate: 'fast',
    toxicity: false,
    careTips:
      'Przycinaj po kwitnieniu, usuń stare pędy, aby pobudzić wzrost nowych.',
    temp: { min: -25, max: 35 },
    lifespan: 'perennial',
  },
  {
  name: 'Hortensja ogrodowa',
  latinName: 'Hydrangea macrophylla',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Hydrangea_macrophylla_01.jpg',
  species: 'shrub',
  soil: ['silty', 'loamy'],
  waterRequirement: 'high',
  wateringDesc: 'Podlewaj 2–3 razy w tygodniu, gleba powinna być stale wilgotna.',
  sunlight: 'partial shade',
  floweringPeriod: { start: 6, end: 9 },
  plantingPeriod: { start: 4, end: 5 },
  heightCm: 150,
  color: ['różowy', 'niebieski', 'biały', 'fioletowy'],
  compatibleWith: ['Hosta', 'Żurawka'],
  soilPh: 6,
  growthRate: 'medium',
  toxicity: false,
  careTips: 'Lubi wilgoć, podlewaj często; przycinaj tylko delikatnie na wiosnę.',
  temp: { min: -15, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Hosta (Funkia)',
  latinName: 'Hosta',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Hosta_undulata.jpg',
  species: 'herb',
  soil: ['loamy', 'silty'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj regularnie, szczególnie w czasie upałów.',
  sunlight: 'partial shade',
  floweringPeriod: { start: 7, end: 8 },
  plantingPeriod: { start: 4, end: 5 },
  heightCm: 60,
  color: ['zielony', 'żółty', 'biały'],
  compatibleWith: ['Hortensja ogrodowa', 'Brunnera'],
  soilPh: 7,
  growthRate: 'medium',
  toxicity: false,
  careTips: 'Usuń kwiaty po przekwitnięciu; ochroń przed ślimakami.',
  temp: { min: -25, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Żurawka ogrodowa',
  latinName: 'Heuchera',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Heuchera_villosa.jpg',
  species: 'herb',
  soil: ['loamy', 'sandy'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj umiarkowanie, unikaj przelania.',
  sunlight: 'partial shade',
  floweringPeriod: { start: 6, end: 8 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 45,
  color: ['czerwony', 'zielony', 'bordowy', 'pomarańczowy'],
  compatibleWith: ['Hosta', 'Brunnera'],
  soilPh: 6.5,
  growthRate: 'medium',
  toxicity: false,
  careTips: 'Co kilka lat odmładzaj kępę, dzieląc ją na wiosnę.',
  temp: { min: -25, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Jaśminowiec wonny',
  latinName: 'Philadelphus coronarius',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Philadelphus_coronarius0.jpg',
  species: 'shrub',
  soil: ['loamy', 'silty'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj raz w tygodniu, częściej podczas suszy.',
  sunlight: 'full sun',
  floweringPeriod: { start: 5, end: 6 },
  plantingPeriod: { start: 3, end: 4 },
  heightCm: 250,
  color: ['biały'],
  compatibleWith: ['Tawuła japońska', 'Berberys'],
  soilPh: 7,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Przycinaj mocno po kwitnieniu, aby pobudzić nowe pędy.',
  temp: { min: -25, max: 35 },
  lifespan: 'perennial',
},
{
  name: 'Forsycja pośrednia',
  latinName: 'Forsythia × intermedia',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Forsythia_intermedia1.jpg',
  species: 'shrub',
  soil: ['loamy', 'sandy'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj umiarkowanie; dobrze znosi przejściową suszę.',
  sunlight: 'full sun',
  floweringPeriod: { start: 4, end: 4 },
  plantingPeriod: { start: 3, end: 4 },
  heightCm: 300,
  color: ['żółty'],
  compatibleWith: ['Jaśminowiec wonny'],
  soilPh: 7,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Przycinać tuż po kwitnieniu, inaczej ograniczysz kwiaty na przyszły rok.',
  temp: { min: -20, max: 35 },
  lifespan: 'perennial',
},
{
  name: 'Piwonia chińska',
  latinName: 'Paeonia lactiflora',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Paeonia_lactiflora_1.jpg',
  species: 'herb',
  soil: ['loamy', 'silty'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj raz na tydzień; nie lubi nadmiaru wody.',
  sunlight: 'full sun',
  floweringPeriod: { start: 5, end: 6 },
  plantingPeriod: { start: 9, end: 10 },
  heightCm: 100,
  color: ['różowy', 'biały', 'czerwony'],
  compatibleWith: ['Róża ogrodowa'],
  soilPh: 6.5,
  growthRate: 'slow',
  toxicity: false,
  careTips: 'Po przekwitnięciu usuń kwiaty; nie przesadzaj bez potrzeby.',
  temp: { min: -30, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Liliowiec ogrodowy',
  latinName: 'Hemerocallis',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/Hemerocallis_Stella_D%27Oro_2.jpg',
  species: 'herb',
  soil: ['loamy', 'sandy'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj co 4–5 dni w czasie upałów.',
  sunlight: 'full sun',
  floweringPeriod: { start: 6, end: 8 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 80,
  color: ['żółty', 'pomarańczowy', 'czerwony'],
  compatibleWith: ['Lawenda', 'Żurawka'],
  soilPh: 6.5,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Usuń stare kwiaty, aby pobudzić kolejne kwitnienie.',
  temp: { min: -20, max: 35 },
  lifespan: 'perennial',
},
{
  name: 'Trawa ozdobna – Kostrzewa sina',
  latinName: 'Festuca glauca',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Festuca_glauca_1.jpg',
  species: 'herb',
  soil: ['sandy', 'loamy'],
  waterRequirement: 'low',
  wateringDesc: 'Podlewaj rzadko; świetnie znosi suszę.',
  sunlight: 'full sun',
  floweringPeriod: { start: 6, end: 7 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 30,
  color: ['niebieski'],
  compatibleWith: ['Rozchodnik', 'Jałowiec'],
  soilPh: 7,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Przycinać delikatnie wiosną, usuń zeschnięte liście.',
  temp: { min: -25, max: 35 },
  lifespan: 'perennial',
},
{
  name: 'Rozchodnik okazały',
  latinName: 'Hylotelephium spectabile',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Sedum_spectabile.jpg',
  species: 'herb',
  soil: ['sandy', 'loamy'],
  waterRequirement: 'low',
  wateringDesc: 'Podlewaj rzadko — idealna roślina na suszę.',
  sunlight: 'full sun',
  floweringPeriod: { start: 8, end: 10 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 60,
  color: ['różowy', 'fioletowy'],
  compatibleWith: ['Kostrzewa sina'],
  soilPh: 7,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Usuń przekwitłe kwiaty jesienią.',
  temp: { min: -25, max: 35 },
  lifespan: 'perennial',
},
{
  name: 'Mięta pieprzowa',
  latinName: 'Mentha × piperita',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Mentha_piperita_001.JPG',
  species: 'herb',
  soil: ['loamy', 'silty'],
  waterRequirement: 'high',
  wateringDesc: 'Podlewaj często, gleba powinna być stale wilgotna.',
  sunlight: 'partial shade',
  floweringPeriod: { start: 7, end: 9 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 60,
  color: ['zielony'],
  compatibleWith: ['Melisa', 'Bazylia'],
  soilPh: 6.5,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Sadź w pojemniku — szybko się rozrasta i może stać się inwazyjna.',
  temp: { min: -15, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Melisa lekarska',
  latinName: 'Melissa officinalis',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Melissa_officinalis_-_leaves.JPG',
  species: 'herb',
  soil: ['loamy', 'silty'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj umiarkowanie; ziemia powinna być lekko wilgotna.',
  sunlight: 'partial shade',
  floweringPeriod: { start: 6, end: 8 },
  plantingPeriod: { start: 4, end: 6 },
  heightCm: 70,
  color: ['zielony'],
  compatibleWith: ['Mięta pieprzowa'],
  soilPh: 6.5,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Przycinaj podczas sezonu dla zagęszczenia rośliny.',
  temp: { min: -15, max: 30 },
  lifespan: 'perennial',
},
{
  name: 'Truskawka ogrodowa',
  latinName: 'Fragaria × ananassa',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Fragaria_x_ananassa20110619_05.jpg',
  species: 'fruit',
  soil: ['loamy', 'silty'],
  waterRequirement: 'medium',
  wateringDesc: 'Podlewaj co 2–3 dni w czasie owocowania.',
  sunlight: 'full sun',
  floweringPeriod: { start: 4, end: 6 },
  plantingPeriod: { start: 3, end: 4 },
  heightCm: 30,
  color: ['czerwony'],
  compatibleWith: ['Czosnek', 'Sałata'],
  soilPh: 6.5,
  growthRate: 'fast',
  toxicity: false,
  careTips: 'Usuwaj rozłogi, jeśli chcesz większe owoce; ściółkuj słomą.',
  temp: { min: -20, max: 30 },
  lifespan: 'perennial',
}
];

async function seed() {
  await connectDB();
  await PlantModel.deleteMany({}); 
  await PlantModel.insertMany(plants);
  console.log("Seed completed!");
  process.exit(0);
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});